[project]
name = "image-fetcher"
version = "1.1.0"
requires-python = ">=3.14"

dependencies = [
    "backoff",
    "click",
    "codetiming",
    "papaya-iiif",
    "requests",
    "stomp.py",
]

[dependency-groups]
test = [
    "pycodestyle",
    "pytest",
    "pytest-cov",
    "pytest-mock",
]

[project.scripts]
image-fetch = "fetcher:cli"
image-fetch-listen = "fetcher:stomp_consumer"
image-fetch-send = "fetcher:stomp_producer"
